spring.application.name=tcbackend


## Database properties
spring.datasource.url=jdbc:postgresql://dpg-dakpdc1594qs73936opg-a.frankfurt-postgres.render.com/talaveracobalto_szfn
spring.datasource.username=developer1
spring.datasource.password=developer1

## Disable the default H2 database
spring.test.database.replace=none

# Spring banner OFF
spring.main.banner-mode=off

# Turns off logs
logging.level.be.vdab.tcbackend.TcbackendApplication=off

## Log the SQL statements
logging.level.org.hibernate.SQL=DEBUG

## Log statements into multiple lines
spring.jpa.properties.hibernate.format_sql=true

## SQL statements highlighted in blue
spring.jpa.properties.hibernate.highlight_sql=true
